[preferred]
default = gtk

org.freedesktop.impl.portal.ScreenCast = gnome
org.freedesktop.impl.portal.Screenshot = gnome

# ignore inhibit cuz gtk portal always returns as success,
# despite gnome portal not having an impl (I think); stopping
# firefox from using wayland idle-inhibitor protocol
org.freedesktop.impl.portal.Inhibit=none
