[ids]

05ac:024f:cd0ad393
05ac:024f:9de9a28a
05ac:024f:b4667538

[main]

leftalt = leftmeta
leftmeta = leftalt
rightalt = rightmeta
rightmeta = rightalt

capslock = overload(control, esc)
x = overload(control, x)


