#!/bin/sh
window=$(hyprctl clients -j | jaq -r '.| map(select(.workspace.name == "special:minimize"))[0].address')
workspace=$(hyprctl  monitors -j | jaq '.[0].activeWorkspace.id')

hyprctl dispatch movetoworkspace "$workspace,address:$window"
