#!/bin/sh

# Get the saved time (or empty) and clock time, in RFC399 format
# This format sorts lexicographically

CLOCKFILE="${CLOCKFILE:-"/storage/.fake-hwclock.data"}"
CTIME=$(date +%s)

if test -f "${CLOCKFILE}" ; then
    FTIME=$(cat "${CLOCKFILE}")
else
    FTIME=0
fi

# if the file time is in the future, use that
setclock() {
	if test "${FTIME}" -ge "${CTIME}" ; then
		echo "loading saved time ${FTIME} over ${CTIME}"
		date --date=@"${FTIME}"
		#date --date="${FTIME}"
		#echo would set clock to $FTIME
	else
		echo "ignoring saved time ${FTIME} over ${CTIME}"
	fi
}


# if current time is greater than what is in the file, save it
saveclock() {
	echo "saving time ${CTIME} over ${FTIME}"
	echo "${CTIME}" > "${CLOCKFILE}"
}


case "$1" in
	load)
		setclock
		;;
	save)
		saveclock
		;;
	tick)
		saveclock
		;;
	*)
		echo "Usage: $0 {load|save|tick}"
		exit 1
		;;
esac
