#!/bin/sh

options='layout: Master
layout: Dwindle
toggle Smart Gaps
toggle Preserve Split
toggle dwindle:pseudotile
Pseudo-tile Window
Change Split Direction
Lock Groups
Unlock Groups
Fake Fullscreen
Show Minimized
OCR'

choice=$(echo "$options" | selectorMenu)

case $choice in
  "layout: Master") hyprctl keyword general:layout master;;
  "layout: Dwindle") hyprctl keyword general:layout dwindle;;
  "toggle Smart Gaps") ~/.config/hypr/scripts/toggleopt dwindle:no_gaps_when_only;;
  "toggle Preserve Split") ~/.config/hypr/scripts/toggleopt dwindle:preserve_split;;
  "toggle dwindle:pseudotile") ~/.config/hypr/scripts/toggleopt dwindle:pseudotile;;
  "Pseudo-tile Window") hyprctl dispatch pseudo;;
  "Change Split Direction") hyprctl dispatch togglesplit;;
  "Lock Groups") hyprctl dispatch lockgroups lock;;
  "Unlock Groups") hyprctl dispatch lockgroups unlock;;
  "Fake Fullscreen") hyprctl dispatch fakefullscreen;;
  "Show Minimized") hyprctl dispatch togglespecialworkspace minimize;;
  "OCR") ocr;;
esac
