#!/bin/sh

usage() {
	echo 'usage:'
	echo "    ${0##.*/} EWW_CMD <window_name> [<eww open args> ...]"
	echo ""
	echo "where:"
	echo "  - EWW_CMD is the magic variable provided by eww"
	echo '  - <eww open args>: see `eww open --help` '
}

cmd="$1"
shift
win="$1"
shift
# open_args="$@"

$cmd close "$win" || $cmd open "$@" "$win"
