# Monitor configuration is done in nix

general {
	border_size = 5
}

debug {
	disable_logs = 0
}

device {
	name = ntrg0001:01-1b96:1b05
	output = eDP-1
}

bind=ALT,period,workspace,+1
bind=ALT,comma,workspace,-1

#bind=ALT,MINUS,workspace,special
bind=ALT,MINUS,togglespecialworkspace,
bind=ALTCONTROL,MINUS,movetoworkspace,special
bind=ALTSHIFT,MINUS,movetoworkspacesilent,special

bind=ALT,GRAVE,pin,
bind=ALT,F,togglefloating,
bind=ALTSHIFT,F,fullscreen,0

bind=SUPER ALT,Q,killactive
bind=SUPER ALT SHIFT,E,exit

bind=ALT,N,cyclenext,
bind=ALT,B,cyclenext,prev

bind=ALT,h,movefocus,l
bind=ALT,l,movefocus,r
bind=ALT,k,movefocus,u
bind=ALT,j,movefocus,d

binde=ALTSHIFT,PERIOD,movetoworkspace,+1
binde=ALTSHIFT,COMMA,movetoworkspace,-1

binde=ALTCONTROL,H,resizeactive,-40 0
binde=ALTCONTROL,L,resizeactive,40 0
binde=ALTCONTROL,K,resizeactive,0 -40
binde=ALTCONTROL,J,resizeactive,0 40


bind=ALT,X,exec,foot

bindm=ALT,mouse:272,movewindow
bindm=ALT,mouse:273,resizewindow

bindm=ALT,touch,movewindow
bindm=CONTROL,touch,resizewindow

gesture = 3, horizontal, workspace
gesture = 3, up, fullscreen
gesture = 3, down, close
gesture = 4, horizontal, resize
gesture = 4, up, move
gesture = 4, pinchout, close

plugin {
	touch_gestures {
		workspace_swipe_fingers = 4
		workspace_swipe_edge = d
		resize_on_border_long_press = true
		sensitivity = 5.0

		# hyprgrass-bind = , edge:l:r, exec, hyprctl notify -1 10000 "rgb(ff1ea3)" "edge: left -> right"
		# hyprgrass-bind = , edge:r:l, exec, hyprctl notify -1 10000 "rgb(ff1ea3)" "edge: right -> left"
		# hyprgrass-bind = , edge:u:d, exec, hyprctl notify -1 10000 "rgb(ff1ea3)" "edge: up -> down"
		hyprgrass-bind = , edge:d:u, exec, hyprctl notify -1 10000 "rgb(ff1ea3)" "edge: down -> up"
		hyprgrass-bind = , pinch:4:i, exec, hyprctl notify -1 10000 "rgb(ff1ea3)" "pinch: 4 in"
		hyprgrass-bind = , pinch:4:o, exec, hyprctl notify -1 10000 "rgb(ff1ea3)" "pinch: 4 out"
		# hyprgrass-bind = , pinch:5:i, exec, hyprctl notify -1 10000 "rgb(ff1ea4)" "pinch: 5 in"
		# hyprgrass-bind = , pinch:5:o, exec, hyprctl notify -1 10000 "rgb(ff1ea4)" "pinch: 5 out"

		hyprgrass-bind = , swipe:3:u, exec, hyprctl notify -1 10000 "rgb(ff1ea3)" "Swipe 3 up"
		hyprgrass-bind = , swipe:4:d, exec, hyprctl notify -1 10000 "rgb(ff1ea3)" "Swipe 4 down"
		hyprgrass-bind = , swipe:4:l, exec, hyprctl notify -1 10000 "rgb(ff1ea3)" "Swipe 4 left"

		hyprgrass-bind = , edge:l:rd, exec, hyprctl notify -1 10000 "rgb(ff1ea3)" "edge: left -> right-down"
		hyprgrass-bind = , edge:l:ru, exec, hyprctl notify -1 10000 "rgb(ff1ea3)" "edge: left -> right-up"

		# hyprgrass-bindl = , edge:l:r, exec, hyprctl notify -1 10000 "rgb(ff1ea3)" "locked edge: left -> right"

		# hyprgrass-bind = , longpress:2, exec, hyprctl notify -1 10000 "rgb(ff1ea3)" "longpress:2"
		# hyprgrass-bindm = , longpress:3, movewindow
		# hyprgrass-bindm = , longpress:4, resizewindow

		hyprgrass-gesture = swipe, 4, up,  fullscreen
		# hyprgrass-gesture = swipe, 3, up,  move
		hyprgrass-gesture = swipe, 3, swipe, workspace
		# hyprgrass-gesture = swipe, 3, down,   close
		hyprgrass-gesture = longpress, 3, swipe , workspace
		hyprgrass-gesture = edge, u, down, special
		hyprgrass-gesture = edge, l, right, workspace
		hyprgrass-gesture = edge, r, left, workspace
		hyprgrass-gesture = edge, u, horizontal, workspace
		# hyprgrass-gesture = pinch, 4, pinchin, close
		# hyprgrass-gesture = pinch, 4, pinchout, float
	}
}
