							############ Window Rules ############
windowrule = float true,match:class ^(.*)(quake)$
windowrule = move 5% 0%,match:class ^(.*)(quake)$
windowrule = size 90% 55%,match:class ^(.*)(quake)$
windowrule = no_blur true,match:class ^(.*)(quake)$
windowrule = workspace special silent,match:class ^(.*)(quake)$

windowrule = workspace 6 silent,match:class ^(sticky)(.*)$
windowrule = float true,match:class ^(sticky-scratch)$
windowrule = size 20% 30%,match:class ^(sticky-scratch)$
windowrule = move 2 70%,match:class ^(sticky-scratch)$

windowrule = float true,match:class ^(.*)(float)$
windowrule = float true,match:class ^(.*)(menu)$
windowrule = pin true,match:class ^(.*)(menu)$

windowrule = float true,match:class ^(com.nextcloud.desktopclient.nextcloud)$
windowrule = float true,match:title ^(Select file)$
windowrule = float true,match:class ^(pavucontrol)$
windowrule = float true,match:class ^(zenity)$
windowrule = float true,match:class ^(pinentry-qt)$
windowrule = float true,match:title ^(Firefox — Sharing Indicator)$]
windowrule = no_initial_focus true,match:title ^(Firefox — Sharing Indicator)$
windowrule = float true,match:title ^(Picture-in-picture)$
windowrule = tile true,match:class ^(neovide)$
windowrule = opacity 0.95,match:class ^(WebCord)$
windowrule = float true,match:class ^(xdragon)$
windowrule = pin true,match:class ^(xdragon)$
windowrule = move cursor 0 0,match:class ^(xdragon)$

windowrule = workspace 9,match:class ^(steam)$
windowrule = float true,match:class ^(steam)$,match:title ^((?!^Steam$).+)$
windowrule = workspace 9 silent,match:class ^(steam)$,match:title ^((?!^Steam$).+)$
windowrule = workspace 10,match:class ^(steam_app)(.*)$
windowrule = fullscreen true,match:class ^(steam_app)(.*)$
windowrule = opaque true,match:class ^(steam_app)(.*)$
windowrule = no_blur true,match:class ^(steam_app)(.*)$
windowrule = idle_inhibit focus,match:class ^(steam_app)(.*)$

# nested Hyprland session
windowrule = workspace 1,match:class ^(wlroots)$

# No gaps when only
workspace = w[tv1], gapsout:0, gapsin:0
workspace = f[1], gapsout:0, gapsin:0
windowrulev2 = bordersize 0, floating:0, onworkspace:w[tv1]
windowrulev2 = rounding 0, floating:0, onworkspace:w[tv1]
windowrulev2 = bordersize 0, floating:0, onworkspace:f[1]
windowrulev2 = rounding 0, floating:0, onworkspace:f[1]
