(atx_h1_marker) @Header1

(atx_h2_marker) @Header2

(atx_h3_marker) @Header3

(atx_h4_marker) @Header4

(atx_h5_marker) @Header5

(atx_h6_marker) @Header6

; code blocks
; kind of a hack: idk how to correctly match closing fences
(fenced_code_block
  ((fenced_code_block_delimiter) @comment))

; quote blocks
((block_quote_marker) @variable
	(#trim! @variable 0 0 0 1)
  (#set! conceal "│"))

((block_continuation) @variable
  (#set! conceal "│")
  (#lua-match? @variable "^>")
  (#trim! @variable 0 0 0 1))

; call-out blocks/admonition
; https://help.obsidian.md/How+to/Use+callouts
; https://learn.microsoft.com/en-us/contribute/markdown-reference#alerts-note-tip-important-caution-warning
(block_quote
  (block_quote_marker)
  (paragraph
    (inline) @_note @comment.note)
  (#lua-match? @_note "^%[%!NOTE%]")
  (paragraph) @comment.note)

(block_quote
  (block_quote_marker)
  (paragraph
    (inline) @_tip @comment.note)
  (#lua-match? @_tip "^%[%!TIP%]")
  (paragraph)? @comment.note)

(block_quote
  (block_quote_marker)
  (paragraph
    (inline) @_warning @comment.warning)
  (#lua-match? @_warning "^%[%!WARNING%]")
  (paragraph) @comment.warning)

; table
(pipe_table_header
  "|" @pipe
  (#set! conceal "│"))

(pipe_table_delimiter_row
  "|" @pipe
  (#set! conceal "│"))

(pipe_table_row
  "|" @pipe
  (#set! conceal "│"))

; (
;  (pipe_table_row
; 	. "|" @pipe1 (#set! conceal " ")
; 	"|" @pipe2 . (#set! conceal " ")
; 	))
; testing
;     (block_quote_marker) @conceal @marker
;     (#set! conceal "▏"))
;
; (block_quote
;     (block_continuation) @conceal @cont
;     (#set! conceal "▏"))
;
; (block_quote
;      (_ (block_continuation) @conceal @nestcont (#set! conceal "▏"))
; )
; tag
; ("#")

; Below this point is copied from nvim runtime

(setext_heading
  (paragraph) @markup.heading.1
  (setext_h1_underline) @markup.heading.1)

(setext_heading
  (paragraph) @markup.heading.2
  (setext_h2_underline) @markup.heading.2)

(atx_heading
  (atx_h1_marker)) @markup.heading.1

(atx_heading
  (atx_h2_marker)) @markup.heading.2

(atx_heading
  (atx_h3_marker)) @markup.heading.3

(atx_heading
  (atx_h4_marker)) @markup.heading.4

(atx_heading
  (atx_h5_marker)) @markup.heading.5

(atx_heading
  (atx_h6_marker)) @markup.heading.6

(info_string) @label

(pipe_table_header
  (pipe_table_cell) @markup.heading)

; (pipe_table_header
;   "|" @punctuation.special)
;
; (pipe_table_row
;   "|" @punctuation.special)
;
; (pipe_table_delimiter_row
;   "|" @punctuation.special)

(pipe_table_delimiter_cell) @punctuation.special

; Code blocks (conceal backticks and language annotation)
(indented_code_block) @markup.raw.block

((fenced_code_block) @markup.raw.block
  (#set! priority 90))

; (fenced_code_block
;   (fenced_code_block_delimiter) @markup.raw.block
;   (#set! conceal "")
;   (#set! conceal_lines "")
;     )

; (fenced_code_block
;   (info_string
;     (language) @label
;     (#set! conceal "")
;     (#set! conceal_lines "")
;     ))

(link_destination) @markup.link.url

[
  (link_title)
  (link_label)
] @markup.link.label

((link_label)
  .
  ":" @punctuation.delimiter)

[
  (list_marker_plus)
  (list_marker_minus)
  (list_marker_star)
  (list_marker_dot)
  (list_marker_parenthesis)
] @markup.list

; NOTE: The following has been commented out due to issues with spaces in the
; list marker nodes generated by the parser. If those spaces ever get captured
; by a different node (e.g. block_continuation) we can safely re-add these
; conceals.
; ;; Conceal bullet points
; ([(list_marker_plus) (list_marker_star)]
;   @punctuation.special
;   (#offset! @punctuation.special 0 0 0 -1)
;   (#set! conceal "•"))
; ([(list_marker_plus) (list_marker_star)]
;   @punctuation.special
;   (#any-of? @punctuation.special "+" "*")
;   (#set! conceal "•"))
; ((list_marker_minus)
;   @punctuation.special
;   (#offset! @punctuation.special 0 0 0 -1)
;   (#set! conceal "—"))
; ((list_marker_minus)
;   @punctuation.special
;   (#eq? @punctuation.special "-")
;   (#set! conceal "—"))
(thematic_break) @punctuation.special

(task_list_marker_unchecked) @markup.list.unchecked

(task_list_marker_checked) @markup.list.checked

; ((block_quote) @markup.quote
;   (#set! priority 90))

([
  (plus_metadata)
  (minus_metadata)
] @keyword.directive
  (#set! priority 90))

[
  (block_continuation)
  (block_quote_marker)
] @punctuation.special

(backslash_escape) @string.escape

(inline) @spell
