name: "Build Packages"
on:
  workflow_dispatch:
  push:
    paths:
      - "flake.lock"
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v26
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
          extra_nix_config: "build-dir = /var/nix"
      - uses: cachix/cachix-action@v12
        with:
          name: horriblename
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
      - run: "nix build .#ghActionsBuilder"
