name: "Build Packages"
on:
  workflow_dispatch:
  push:
    paths:
      - "flake.lock"
jobs:
  build_packages:
    runs-on: ubuntu-latest
    steps:
      - name: Maximize build space
        uses: easimon/maximize-build-space@master
        with:
          root-reserve-mb: 512
          swap-size-mb: 1024
          build-mount-path: '/nix'
          remove-dotnet: 'true'
          remove-android: 'true'
          remove-haskell: 'true'
          remove-codeql: 'true'
          remove-docker-images: 'true'

      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v26
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}

      - name: Set nix daemon tmpdir path
        run: |
          sudo mkdir -p /nix/tmpdir
          sudo chown "$(whoami)" /nix/tmpdir

          cat > override.conf <<EOF
          [Service]
          Environment="TMPDIR=/nix/tmpdir"
          EOF
          sudo mkdir /etc/systemd/system/nix-daemon.service.d/
          sudo mv override.conf /etc/systemd/system/nix-daemon.service.d/override.conf
          sudo systemctl daemon-reload
          sudo systemctl restart nix-daemon

      - uses: cachix/cachix-action@v12
        with:
          name: horriblename
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
      - run: "nix build --no-link --print-out-paths .#ghActionsBuilder | cachix push horriblename"
      - run: "cachix push horriblename"
      - run: "nix-collect-garbage --delete-old"
      - run: "nix build --no-link .#ghActionsBuilder2"
