name: "Build Packages"
on:
  workflow_dispatch:
  push:
    paths:
      - "flake.lock"
jobs:
  build_packages:
    runs-on: ubuntu-latest
    steps:
      - name: Maximize build space
        uses: easimon/maximize-build-space@master
        with:
          root-reserve-mb: 31744
          temp-reserve-mb: 20480
          remove-dotnet: "true"
          remove-android: "true"
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v26
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
          extra_nix_config: "build-dir = /var/nix"
      - uses: cachix/cachix-action@v12
        with:
          name: horriblename
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
      - run: "nix build .#ghActionsBuilder"
      - run: "cachix push"
      - run: "nix-collect-garbage --delete-old"
      - run: "nix build .#ghActionsBuilder2"
