name: update-flake-lock
on:
  workflow_dispatch: # allows manual triggering
  schedule:
    - cron: "0 0 * * 0" # runs weekly on Sunday at 00:00

jobs:
  lockfile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v1
      - uses: cachix/cachix-action@v12
        with:
          name: horriblename
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
      - name: Update flake.lock
        uses: DeterminateSystems/update-flake-lock@v19
        with:
          pr-title: "Update flake.lock" # Title of PR to be created
          pr-labels: | # Labels to be set on the PR
            dependencies
            automated
      - name: Rebuild packages
        run: "nix build .#ghActionsBuilder"
